/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.std;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class App {

    public static void main(String[] args) {
        System.out.println("..:: servidor TCP ::..");
        int porta = 1234;

        try(ServerSocket serverSocket = new ServerSocket(porta)){

            while (true){
                //aguardando
                Socket clientSocket = serverSocket.accept();

                Thread t = new Thread(new ThreadServidor(clientSocket));

                 //dispara thread
                t.start();



            }

        } catch (Exception e) {
            System.out.println("Erro" + e.toString());
        }
    }
}